### ISSUE TITLE
Does this work?

### ISSUE THREAD

**Issue by anildigital** [membraneframework/membrane-element-icecast#2]
I scanned code and looks like there is no implementation yet?

**Comment by kanes115** [comment]
Hello, @anildigital!
Unfortunately not yet. This is still being developed. 

You can always take a look at these repositories meanwhile: https://github.com/membraneframework/membrane-server-icecast/pull/2 and https://github.com/membraneframework/membrane-protocol-icecast/pull/2.

We should finish developing the icecast element soon, though!

**Comment by anildigital** [comment]
@kanes115 Thanks for the update. I am watching for its changes.
